name: mdoenv
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.12.1
  - asttokens=3.0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.20
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.4
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freeglut=3.8.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - ipykernel=7.2.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.4
  - libffi=3.4.4
  - libglib=2.86.3
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkrb5=1.22.1
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libpq=17.6
  - libsodium=1.0.20
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - lz4-c=1.9.4
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nest-asyncio=1.6.0
  - numpy=2.4.2
  - numpy-base=2.4.2
  - openssl=3.6.1
  - packaging=25.0
  - pandas=3.0.0
  - parso=0.8.6
  - pcre2=10.46
  - pillow=12.0.0
  - pip=26.0.1
  - pixman=0.46.4
  - platformdirs=4.9.2
  - prompt-toolkit=3.0.52
  - psutil=7.2.2
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pywin32=311
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - scipy=1.17.0
  - setuptools=80.10.2
  - sip=6.12.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.6.0
  - wheel=0.46.3
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - cloudpickle==3.1.2
      - pygad==3.5.0
prefix: C:\Users\mayar\anaconda3\envs\mdoenv
